### ISSUE TITLE
Add code/instructions for debugging

### ISSUE THREAD

**Issue by markusr** [temoto/gpio-cdev-go#1]
First of all thank you for this code! 👍 

How do you test / debug this code? As I understand ```delve``` is not working under ARM. 

I did some tests some time ago where I used ```gpio-mockup``` to generate a virtual device under x64. I will try to find my notes on how to do this.

**Comment by temoto** [comment]
@markusr yeah sorry, test situation right now is a shame. I could at least make some functional tests in form of executable. Deadline pressure is excuse of the month.

Please state more specific task I could help with. Something doesn't work and you need to find why? 

Or do you need to mock up this lib for your test suite? I went with mocking whole hardware code, example here https://github.com/temoto/vender/tree/76ec9f3fa219a6fc4c4af597ee88d0a9ed5b04c0/hardware/lcd  TL;DR: think io.Reader fed with os.File in production and StringReader in tests.

**Comment by markusr** [comment]
@temoto 
My idea was to add unit tests. Therefore we would need a ```/dev/gpiochip``` to test against.  This is problematic because on desktop computers there is normally no device available. 

A possible solution is a linux kernel module called ```gpio-mockup```, see [mainline kernel](https://github.com/torvalds/linux/blob/master/drivers/gpio/gpio-mockup.c). This module simulates a "real" ```/dev/gpiochip```.

I tried to get this mockup module loaded under ubuntu 18.04 but I have not succeeded so far.

**Comment by temoto** [comment]
@markusr understood. Yeah, I don't have `/dev/gpiochip` on laptop either. It should be very simple to buildroot smallest Linux with that mock device and run it in qemu on anything including cloud CI (Travis here and now).

`zgrep CONFIG_GPIO_MOCKUP /proc/config.gz` ?

I'll make some tests, but it's not a priority right now. Sorry.

**Comment by markusr** [comment]
@temoto 
A qemu is also a good approach. 

On my machine it is:
```
$ grep CONFIG_GPIO_MOCKUP /boot/config-$(uname -r)
# CONFIG_GPIO_MOCKUP is not set
```

> I'll make some tests, but it's not a priority right now. Sorry.

No problem I just wanted to give some input.

**Comment by temoto** [comment]
@markusr good news on gpio-mockup. It's not advertised much, you must provide at least one parameter to enable that kernel module: `modprobe gpio-mockup gpio_mockup_ranges=0,64`

Or if `CONFIG_GPIO_MOCKUP=y`, add parameter on kernel command line: `gpio-mockup.gpio_mockup_ranges=0,64`

You'll get 64-0=64 virtual pins.

So testing plan:
- [x] buildroot minimal gpio-mockup capable kernel + system image
- [x] actually write tests :-)
- [x] insert custom program (test suite) as init
- [x] make it all work on CI with nice compilation cache

I just have to mention these super helpful sources:
- [How to build a custom Linux kernel for QEMU](http://mgalgs.github.io/2015/05/16/how-to-build-a-custom-linux-kernel-for-qemu-2015-edition.html)
- [A note about the new linux kernel interface - gpio uapi](https://weekly-geekly.github.io/articles/351512/index.html)
- [Totally static go builds](http://blog.wrouesnel.com/articles/Totally%20static%20Go%20builds/)

**Comment by temoto** [comment]
@markusr it's done and merged. You are very welcome to upgrade actual test code. Should be easy now that infrastructure is there. Of course it runs in pull requests.
